version: "3.9"
services:
  pg:
    image: postgres:13
    restart: "always"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: fire-station
    ports:
      - 4444:5432
    volumes:
      - ./db:/var/lib/postgresql/data
